version: '3.9'

services:
  api:
    build:
      context: .
      dockerfile: prod.Dockerfile
    command: gunicorn chicpic.wsgi:application -w 4 -b 0.0.0.0:8000 --timeout 300 --log-level=info
    restart: always
    volumes:
      - .:/app
      - static_volume:/app/static
      - media_volume:/app/media
    env_file:
      - .env
    ports:
      - "8000:8000"
    depends_on:
      - db
  db:
    image: postgres:15
    restart: always
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_DB=${DB_NAME}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
  nginx:
    build: ./nginx
    restart: always
    ports:
      - "80:80"
    volumes:
      - static_volume:/app/static
      - media_volume:/app/media
    depends_on:
      - api

volumes:
  postgres_data:
  static_volume:
  media_volume:
