# Generated by Django 4.1.6 on 2023-02-15 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0004_trackedproduct_savedproduct'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='image',
            field=models.ImageField(default='default.png', upload_to='category_images/'),
        ),
    ]
