# Generated by Django 4.1.6 on 2023-05-17 13:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clothing', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sizing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('option', models.CharField(choices=[('Bust', 'Bust'), ('Waist', 'Waist'), ('Inseam', 'Inseam'), ('Hips', 'Hips'), ('Shoulder', 'Shoulder'), ('Chest', 'Chest'), ('Height', 'Height')], max_length=20)),
                ('value', models.PositiveSmallIntegerField()),
                ('variant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sizings', to='clothing.variant')),
            ],
            options={
                'unique_together': {('variant', 'option')},
            },
        ),
        migrations.DeleteModel(
            name='SizeGuide',
        ),
    ]
