# Generated by Django 4.1.6 on 2023-05-22 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clothing', '0002_sizing_delete_sizeguide'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='category',
        ),
        migrations.AddField(
            model_name='product',
            name='category',
            field=models.ManyToManyField(related_name='products', to='clothing.category'),
        ),
    ]
