# Generated by Django 4.1.6 on 2023-02-06 15:51

from django.db import migrations, models
import django.db.models.deletion
import clothing.models


class Migration(migrations.Migration):

    dependencies = [
        ('clothing', '0002_alter_category_gender'),
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=80)),
                ('description', models.CharField(blank=True, max_length=350)),
                ('image', models.ImageField(upload_to=clothing.models.variant_image_upload_path)),
                ('link', models.URLField(max_length=256)),
                ('original_price', models.DecimalField(decimal_places=2, max_digits=5)),
                ('final_price', models.DecimalField(decimal_places=2, max_digits=5, null=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='clothing.brand')),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products', to='clothing.category')),
            ],
        ),
    ]
