# Generated by Django 4.1.6 on 2023-05-22 16:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clothing', '0003_remove_product_category_product_category'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='category',
            new_name='categories',
        ),
    ]
