# Generated by Django 4.1.6 on 2023-06-10 20:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clothing', '0004_rename_category_product_categories'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sizing',
            name='option',
            field=models.CharField(choices=[('Bust', 'Bust'), ('Waist', 'Waist'), ('Inseam', 'Inseam'), ('Hips', 'Hips'), ('Shoulder', 'Shoulder'), ('Chest', 'Chest'), ('Height', 'Height'), ('Neck', 'Neck'), ('Shoe Size', 'Shoe Size')], max_length=20),
        ),
        migrations.AlterField(
            model_name='sizing',
            name='value',
            field=models.DecimalField(decimal_places=1, max_digits=4),
        ),
    ]
