# Generated by Django 4.1.6 on 2023-02-15 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clothing', '0005_category_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='image',
            field=models.ImageField(upload_to='category_images/'),
        ),
    ]
