# Generated by Django 4.2.2 on 2023-06-19 08:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clothing', '0005_alter_sizing_option_alter_sizing_value'),
    ]

    operations = [
        migrations.RenameField(
            model_name='variant',
            old_name='color',
            new_name='color_hex',
        ),
    ]
