# Generated by Django 4.2.2 on 2023-06-19 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clothing', '0006_rename_color_variant_color_hex'),
    ]

    operations = [
        migrations.AddField(
            model_name='variant',
            name='size',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
