# Generated by Django 4.1.6 on 2023-02-18 09:48

from django.db import migrations, models
import django.db.models.deletion
import clothing.models


class Migration(migrations.Migration):

    dependencies = [
        ('clothing', '0006_alter_category_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Shop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('image', models.ImageField(upload_to=clothing.models.shop_image_upload_path)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ('name',),
            },
        ),
        migrations.RemoveField(
            model_name='product',
            name='brand',
        ),
        migrations.DeleteModel(
            name='Brand',
        ),
        migrations.AddField(
            model_name='product',
            name='shop',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='products', to='clothing.shop'),
            preserve_default=False,
        ),
    ]
