# Generated by Django 4.2.2 on 2023-08-07 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clothing', '0007_variant_size'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trackedvariant',
            name='tracked_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
