# Generated by Django 4.1.6 on 2023-03-28 13:21

import clothing.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clothing', '0009_remove_product_final_price_remove_product_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shop',
            name='image',
            field=models.ImageField(default='default.png', upload_to=clothing.models.shop_image_upload_path),
        ),
    ]
