# Generated by Django 4.2.2 on 2023-08-20 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clothing', '0009_savedvariant_is_deleted_trackedvariant_is_deleted'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ('priority',), 'verbose_name_plural': 'Categories'},
        ),
        migrations.AddField(
            model_name='category',
            name='priority',
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
