# Generated by Django 4.2.2 on 2023-11-15 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clothing', '0011_product_is_deleted_product_original_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='original_id',
            field=models.BigIntegerField(unique=True),
        ),
        migrations.AlterField(
            model_name='variant',
            name='original_id',
            field=models.BigIntegerField(unique=True),
        ),
    ]
