# Generated by Django 4.1.6 on 2023-04-04 15:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clothing', '0011_alter_category_options_alter_category_gender'),
    ]

    operations = [
        migrations.RenameField(
            model_name='attribute',
            old_name='attribute',
            new_name='name',
        ),
        migrations.AlterUniqueTogether(
            name='attribute',
            unique_together={('variant', 'name')},
        ),
    ]
