# Generated by Django 4.1.6 on 2023-04-05 08:17

import clothing.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clothing', '0012_rename_attribute_attribute_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='variant',
            name='image',
            field=models.ImageField(max_length=200, upload_to=clothing.models.variant_image_upload_path),
        ),
    ]
