# Generated by Django 4.2.2 on 2024-01-01 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clothing', '0012_alter_product_original_id_alter_variant_original_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='variant',
            name='final_price',
            field=models.DecimalField(decimal_places=2, max_digits=6),
        ),
        migrations.AlterField(
            model_name='variant',
            name='original_price',
            field=models.DecimalField(decimal_places=2, max_digits=6),
        ),
    ]
