# Generated by Django 4.1.6 on 2023-04-05 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clothing', '0013_alter_variant_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='variant',
            name='image',
        ),
        migrations.AddField(
            model_name='variant',
            name='image_src',
            field=models.URLField(default='default.png', max_length=300),
            preserve_default=False,
        ),
    ]
