# Generated by Django 4.2.16 on 2024-09-27 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clothing', '0014_alter_product_brand_alter_product_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='shop',
            name='deleted_at',
            field=models.DateTimeField(blank=True, editable=False, null=True),
        ),
        migrations.AddField(
            model_name='shop',
            name='is_deleted',
            field=models.BooleanField(default=False, editable=False),
        ),
    ]
