# Generated by Django 4.1.6 on 2023-04-06 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clothing', '0014_remove_variant_image_variant_image_src'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attribute',
            name='value',
            field=models.CharField(max_length=40),
        ),
        migrations.AlterField(
            model_name='product',
            name='description',
            field=models.TextField(blank=True),
        ),
    ]
