# Generated by Django 4.1.6 on 2023-04-06 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clothing', '0015_alter_attribute_value_alter_product_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='shop',
            name='website',
            field=models.URLField(default='https://www.chicpic.app'),
            preserve_default=False,
        ),
    ]
