# Generated by Django 4.1.6 on 2023-04-21 12:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clothing', '0017_savedvariant_trackedvariant_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ('-id',)},
        ),
        migrations.AlterModelOptions(
            name='variant',
            options={'ordering': ('-id',)},
        ),
        migrations.DeleteModel(
            name='Attribute',
        ),
    ]
