# Generated by Django 4.1.6 on 2023-04-22 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clothing', '0018_alter_product_options_alter_variant_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='variant',
            name='is_available',
            field=models.BooleanField(verbose_name='Available'),
        ),
    ]
