# Generated by Django 4.1.6 on 2023-04-22 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clothing', '0020_attribute_product_created_at_variant_option1_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='productattribute',
            options={'ordering': ('position',)},
        ),
        migrations.RemoveConstraint(
            model_name='productattribute',
            name='valid_order',
        ),
        migrations.RemoveConstraint(
            model_name='productattribute',
            name='unique_product_order',
        ),
        migrations.RenameField(
            model_name='productattribute',
            old_name='attribute_order',
            new_name='position',
        ),
        migrations.AddConstraint(
            model_name='productattribute',
            constraint=models.CheckConstraint(check=models.Q(('position__in', [0, 1, 2, 3])), name='valid_position'),
        ),
        migrations.AddConstraint(
            model_name='productattribute',
            constraint=models.UniqueConstraint(condition=models.Q(('position__gt', 0)), fields=('product', 'position'), name='unique_product_position'),
        ),
    ]
