# Generated by Django 4.1.6 on 2023-05-02 18:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clothing', '0021_alter_productattribute_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='attributes',
        ),
    ]
