# Generated by Django 4.1.6 on 2023-02-19 12:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_otp'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserAdditional',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weight', models.PositiveSmallIntegerField()),
                ('height', models.PositiveSmallIntegerField()),
                ('birth_date', models.DateField()),
                ('bust_size', models.PositiveSmallIntegerField()),
                ('waist_size', models.PositiveSmallIntegerField()),
                ('hip_size', models.PositiveSmallIntegerField()),
                ('leg_length', models.PositiveSmallIntegerField()),
                ('shoe_size', models.PositiveSmallIntegerField()),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='additional', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='TrouserFit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fit_type', models.CharField(choices=[('Skinny', 'Skinny'), ('Slim', 'Slim'), ('Normal', 'Normal'), ('Loose', 'Loose'), ('Tapered', 'Tapered')], max_length=10)),
                ('user_additional', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.useradditional')),
            ],
            options={
                'unique_together': {('user_additional', 'fit_type')},
            },
        ),
        migrations.CreateModel(
            name='ShirtFit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fit_type', models.CharField(choices=[('Slim', 'Slim'), ('Regular', 'Regular')], max_length=10)),
                ('user_additional', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.useradditional')),
            ],
            options={
                'unique_together': {('user_additional', 'fit_type')},
            },
        ),
    ]
