# Generated by Django 4.1.6 on 2023-02-21 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_useradditional_trouserfit_shirtfit'),
    ]

    operations = [
        migrations.AddField(
            model_name='useradditional',
            name='gender_interested',
            field=models.CharField(choices=[('F', 'Female'), ('M', 'Male')], default='M', max_length=10),
            preserve_default=False,
        ),
    ]
