# Generated by Django 4.1.6 on 2023-02-25 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_useradditional_gender_interested'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useradditional',
            name='shoe_size',
            field=models.DecimalField(decimal_places=1, max_digits=3),
        ),
    ]
