# Generated by Django 4.1.6 on 2023-02-26 09:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_alter_useradditional_shoe_size'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='useradditional',
            name='user',
        ),
        migrations.DeleteModel(
            name='ShirtFit',
        ),
        migrations.DeleteModel(
            name='TrouserFit',
        ),
        migrations.DeleteModel(
            name='UserAdditional',
        ),
    ]
