# Generated by Django 4.2.2 on 2023-06-12 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0007_useradditional_trouserfit_shirtfit'),
    ]

    operations = [
        migrations.RenameField(
            model_name='useradditional',
            old_name='hip_size',
            new_name='hips_size',
        ),
        migrations.RenameField(
            model_name='useradditional',
            old_name='leg_length',
            new_name='inseam',
        ),
        migrations.AddField(
            model_name='useradditional',
            name='chest_size',
            field=models.PositiveSmallIntegerField(default=90),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='useradditional',
            name='shoulder_size',
            field=models.PositiveSmallIntegerField(default=45),
            preserve_default=False,
        ),
    ]
