# Generated by Django 4.2.2 on 2023-08-16 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0008_rename_hip_size_useradditional_hips_size_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useradditional',
            name='bust_size',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='useradditional',
            name='chest_size',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
    ]
