# Generated by Django 4.2.16 on 2024-09-25 14:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0012_user_deleted_at_user_is_deleted'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeletedUser',
            fields=[
            ],
            options={
                'verbose_name': 'Deleted User',
                'verbose_name_plural': 'Deleted Users',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('user.user',),
        ),
    ]
